# Generated by Django 5.1.6 on 2025-05-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_usersearchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersearchhistory',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
